# Generated by Django 5.0.4 on 2024-04-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('order',)},
        ),
    ]
